### ISSUE TITLE
package not working with typescript@3.0.1

### ISSUE THREAD

**Issue by nikhilpuria** [stipsan/compute-scroll-into-view#74]
The global declaration of Element {
  host: any
}

is conflicting with the new typescript version(3.0.1) where host is of string type.

Getting the following errors while using this package

/node_modules/typescript/lib/lib.dom.d.ts:5547:11 - error TS2320: Interface 'HTMLAnchorElement' cannot simultaneously extend types 'HTMLElement' and 'HTMLHyperlinkElementUtils'.
  Named property 'host' of types 'HTMLElement' and 'HTMLHyperlinkElementUtils' are not identical.

/node_modules/typescript/lib/lib.dom.d.ts:5658:11 - error TS2320: Interface 'HTMLAreaElement' cannot simultaneously extend types 'HTMLElement' and 'HTMLHyperlinkElementUtils'.
  Named property 'host' of types 'HTMLElement' and 'HTMLHyperlinkElementUtils' are not identical.

**Comment by stipsan** [comment]
I don't know why this haven't shown up on the TS tests done on this repo, as well as on `scroll-into-view-if-needed` and `scroll-into-view-if-needed-website`, but I have created a PR to attempt fixing it by removing this global Element.host definition.

**Comment by stipsan** [comment]
Looks like it's because none of the tests are testing a `<a>` element, that would make sense 🤔
